### ISSUE TITLE
Data Problem

### ISSUE THREAD

**Issue by wenjiemao1207** [AdaCompNUS/pfnet#1]
Dear Professors:
       I'm running this project,but there's something wrong with the DataLossError when I train the dataset.Can you help me solve the problem,thank you very much.
      The Error code is DataLossError: corrupted record at 15458974733

                                                                                                                                         Yours
                                                                                                                                       Sincerely

**Comment by karkuspeter** [comment]
It looks like your data file might be corrupt. Which dataset are you using?
Could you try to download it again, or try with another dataset?

**Comment by wenjiemao1207** [comment]
The data set with errors is train.tfrecords. It may be that the data set is too large, and datalosserror will appear in every training. However, the location of the errors in each downloaded data set is different, which may be that there is an error in the download. I'm trying again. Thank you, professor.
